sudo: false
language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
before_script:
  - chmod 777 ./travis/setup_arangodb.sh
  - ./travis/setup_arangodb.sh
after_script:
  - killall -9 arangod_x86_64
script:
  - sbt clean test
  - sbt coverage driver/test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete